### PR TITLE
Empty sensor handling

### PR DESCRIPTION
**Pull request by frankysan**
Added check for empty sensor

### CODE REVIEW

**Review by Miicroo — CHANGES_REQUESTED** [review]
Looks good! You can merge your other PR since it looks good too, and then I suspect that you will have "conflicts" between this branch and master that you will have to rebase (hence the "request change" reply here, nothing wrong with the PR itself) :)

**Comment by frankysan** [comment]
Sure thing, just as soon as I figure it out :) Just learning GitHub here :)

**Comment by frankysan** [comment]
I think I need to be added as contributor in order to merge, since I won't have write access otherwise.

**Review by Miicroo — APPROVED** [review]

**Comment by Miicroo** [comment]
> I think I need to be added as contributor in order to merge, since I won't have write access otherwise.

Aha! I merged it since it was already ready! Can merge this one too, seems it doesn't have any conflicts

**Pull request merged**
